### ISSUE TITLE
ActivitySupportTestCase AttributeError: 'QuerySet' object has no attribute 'get_latest_by'

### ISSUE THREAD

**Issue by jallman112** [w-a-r-m-inventory-system/Food-Pantry-Inventory#141]
Tests are throwing `'QuerySet' object has no attribute 'get_latest_by'` on current dev branch
```
======================================================================
ERROR: test_box_consume (Food-Pantry-Inventory.fpiweb.tests.test_support_activity.ActivitySupportTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jallman112/PycharmProjects/Food-Pantry-Inventory/fpiweb/tests/test_support_activity.py", line 151, in test_box_consume
    ba.box_empty(empty_box.id)
  File "/home/jallman112/PycharmProjects/Food-Pantry-Inventory/fpiweb/support/BoxActivity.py", line 163, in box_empty
    self.activity = Activity.objects.filter(
AttributeError: 'QuerySet' object has no attribute 'get_latest_by'

----------------------------------------------------------------------
```

**Comment by deeppunster** [comment]
I will try to fix this in the very near future.

**Comment by deeppunster** [comment]
Pe #154 fixed this issue.
